name: Deploy to Github Pages

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 19

    - uses: pnpm/action-setup@v2
      name: Install pnpm
      id: pnpm-install
      with:
        version: 10
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install
      
    - name: Build
      run: |
         pnpm build
         echo "✅ Build complete"
         ls -la

      
    - name: Deploy to GitHub Pages
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

        # Create a temporary directory for gh-pages
        mkdir gh-pages-temp
        cd gh-pages-temp

        # Initialize a new Git repo and check out gh-pages branch
        git init
        git checkout -b gh-pages

        # Copy build output from previous step
        cp -r ../dist/* .

        # Commit and push to gh-pages
        git add --all
        git commit -m "Automatic Deploy"
        git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" gh-pages
      shell: bash
